version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    restart: always
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - web

  celery_beat:
    build: .
    restart: always
    tty: true
    command: celery -A config beat -l INFO
    depends_on:
      - redis
      - web

  cw8db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env

  web:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 && python manage.py collectstatic "
    ports:
      - "8000:8000"
    volumes:
      - .:/cw8
    depends_on:
      cw8db:
        condition: service_healthy
    env_file:
      - .env


volumes:
  pg_data:
